:art: Add default drafter config
Staffbase/gha-workflows pull request #156
Opened 2023-08-23 19:50 UTC by flaxel

### Type of Change

- [ ] Bugfix
- [ ] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation

### Description

### Checklist

- [ ] Add relevant labels (for example type of change or patch/minor/major)
- [ ] Make sure not to introduce some mistakes
- [ ] Update documentation
- [ ] Review the [Contributing Guideline](../blob/main/CONTRIBUTING.md) and sign CLA
- [ ] Reference relevant issue(s) and close them after merging

2023-08-24 06:34 UTC, timdittler requested changes

2023-08-24 06:34 UTC, timdittler commented on .github/workflows/template_release_drafter.yml
> +          mkdir .github
```suggestion
          mkdir -p .github
```
Avoid breaking the script because of existing directory

2023-08-24 09:43 UTC, timdittler approved these changes

2023-08-28 06:56 UTC, stefanmeschke approved these changes

2023-08-30 06:43 UTC, merged