:sparkles: add jira tagging workflow
Staffbase/gha-workflows pull request #24
Opened 2022-05-02 12:14 UTC by flaxel

### Type of Change

- [ ] Bugfix
- [x] Enhancement / new feature
- [ ] Refactoring
- [ ] Documentation

### Description

- add jira release tagging workflow

### Checklist

- [x] Add relevant labels (for example type of change or patch/minor/major)
- [x] Make sure not to introduce some mistakes
- [x] Update documentation
- [x] Review the [Contributing Guideline](../blob/main/CONTRIBUTING.md) and sign CLA
- [ ] Reference relevant issue(s) and close them after merging

2022-05-05 07:25 UTC, 0x46616c6b requested changes
I'm not sure to add this workflow here. The GH Action behind are private and could not used by any others.

2022-05-05 07:30 UTC, flaxel commented
@0x46616c6b I had the same thought. But since we use the same configuration everywhere and copy the text again and again, I would have found it quite nice to also make the maintainability of the action easier.

2022-05-10 10:50 UTC, 0x46616c6b approved these changes

2022-05-10 19:11 UTC, soemo commented on README.md
> +
We can add some more information hereabout the changelog process. Maybe a link to a Confluence page ....

2022-05-16 09:12 UTC, merged